version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  # 这个worker是用c#写的真是奇怪
  worker:
    build: ./worker

  db:
    image: postgres:9.4

  result:
    build: ./result
    # nodemon 应用可以自动监控nodejs应用，检测到变化后自动restart应用
    command: nodemon --debug server.js
    # 将result挂载到容器内app，当result内代码改变的时候，容器内app自动restart。实现对容器内的应用的调试
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
